from pathlib import Path
from typing import Dict, List
from sbom_forge.graph.models import ScanResult, Ecosystem


def generate_hardened_npmrc(target_dir: Path) -> Path:
    out_file = target_dir / ".npmrc"
    content = """# Auto-generated by sbom-forge
# Supply Chain Security Hardening Configuration

package-lock=true
save-exact=true
audit=true
fund=false
ignore-scripts=false
engine-strict=true
"""
    with open(out_file, "w", encoding="utf-8") as f:
        f.write(content)

    return out_file


def generate_pip_constraints(result: ScanResult, target_dir: Path) -> Path:
    out_file = target_dir / "constraints.txt"
    lines = ["# Auto-generated by sbom-forge\n", "# Pinned dependency constraints\n\n"]

    for pkg in result.nodes.values():
        if pkg.ecosystem == Ecosystem.PYPI:
            if pkg.integrity_hash:
                lines.append(f"{pkg.name}=={pkg.version} --hash={pkg.integrity_hash}\n")
            else:
                lines.append(f"{pkg.name}=={pkg.version}\n")

    with open(out_file, "w", encoding="utf-8") as f:
        f.writelines(lines)

    return out_file
